class CustomeReportGenerator:

    def __init__(self):
        pass


    def reportGenerator(self,testcaseName):

        preExistingTemplete="<html>"+"<head>"+"<style"
        preExistingTemplete +="td {vertical-align: middle;font-size: 15px;word-wrap:break-word;}"
        preExistingTemplete += "th {vertical-align: top;background: #d1ecf1;color: black;}"
        preExistingTemplete += ".topcorner{position:absolute;top:0;right:0;width: 3%;cursor:pointer;z-index: +1;}"
        preExistingTemplete += ".black_overlay{display: none;position: fixed;top: 0%;left: 0%;width: 100%;height: 100%;background-color: grey;z-index:1001;-moz-opacity: 0.8;opacity:.80;filter: alpha(opacity=80);}"
        preExistingTemplete += " .white_content {display: none;position: fixed;top: 10%;left:20px;width: 85%;height: 60%;padding: 16px;border: 2px solid ged;background-color: white;z-index:1002;overflow: auto;}"
        preExistingTemplete += "table td > div > table{width:100%;table-layout:fixed;}"
        preExistingTemplete += "table td > div > table td > div{overflow-y:auto; min-height: 10px; max-height: 200px;}"
        preExistingTemplete += "pre {box-sizing: border-box;width: 100%;padding: 0;margin: 0;overflow: auto;overflow-y: hidden;font-size: 14px;line-height: 20px;background: #efefef;border: 1px solid #777;padding: 10px;color: #333;}"
        preExistingTemplete += "div.beta{top: 25%;position: absolute;text-align: center;width: 100%;justify-content: center;background-color: #ffc;opacity: 0.3;transform: rotate(-10deg) skew(-10deg);word-break: break-all;font-size: 100px;font-weight: bold;z-index:+1;pointer-events:none;}"
        preExistingTemplete += "div#screenshot{z-index:2002;height: auto;top: auto;left:10%;padding:0px;width:80%;}"
        preExistingTemplete += "div#screenshotoverlay{z-index:2001;}"
        preExistingTemplete += "img#the-image{width:100%;cursor:pointer;}"
        preExistingTemplete += "div.image-text{top: 20%;position: absolute;text-align: center;width: 100%;justify-content: center;background-color: #ffc;opacity: 0.2;transform: rotate(-10deg) skew(-10deg);word-break: break-all;font-size: 40px;font-weight: bold;}"
        preExistingTemplete += "div.image-text:hover{display: none;}"
        preExistingTemplete += "button.prev, button.next{position:absolute;top:50%;padding-top:20px;padding-bottom:20px;opacity: 0.7;}"
        preExistingTemplete += "button.prev:hover, button.next:hover{opacity: 1;}"
        preExistingTemplete += "button.prev{left: 0;}"
        preExistingTemplete += "button.next{right:0;}"
        preExistingTemplete += "</style>"
        preExistingTemplete += "</head>"
        preExistingTemplete += "<body>"
        preExistingTemplete += "<div id='Puytest' class='white_content' style='display: block;'>"
        preExistingTemplete += "<div style='background-color:#d1ecf1;text-align:center'><p>TC_SM-109608_RegistrationToken_withoutCustomer_windows__1_ Create Customer through WS</p></div>"
        preExistingTemplete += "<table border='1' cellpadding='8' cellspacing='0'>"
        preExistingTemplete += "<tbody>"
        preExistingTemplete += "<tr>"
        preExistingTemplete += "<th width='15%'>API Name</th>"
        preExistingTemplete += "<th width='20%'>Inputs</th>"
        preExistingTemplete += "<th width='10%'>Exp. Ret. Code</th>"
        preExistingTemplete += "<th width='10%'>Act Ret. Code</th>"
        preExistingTemplete += "<th width='25%'>Exp Respone</th>"
        preExistingTemplete += "<th width='25%'>Act Response</th>"
        preExistingTemplete += "<th width='10%'>Response Time</th>"
        preExistingTemplete += "<th width='10%'>Status</th>"
        preExistingTemplete += "<th width='15%'>Comments</th>"
        preExistingTemplete += "<th width='15%'>User Vars</th>"
        preExistingTemplete += "<th width='10%'>ScreenShot</th>"
        preExistingTemplete += "</tr>"
        preExistingTemplete += "<tr>"
        preExistingTemplete += "<td>UpdateXMLData</td>"
        preExistingTemplete += "<td width='150px'>"
        preExistingTemplete += "<div>[xml=contact.xml, tags=name;password;emailId, value=endcustkeyclock{{Rint5}}{{Rint5}}{{Rint5}};Thales@123;endcustkeyclock{{Rint5}}{{Rint5}}{{Rint5}}@sntinelcloud.com]</div>"
        preExistingTemplete += "</td>"
        preExistingTemplete += "<td>200</td>"
        preExistingTemplete += "<td>200</td>"
        preExistingTemplete += "<td width='150px'><div><div></div></div></td>"
        preExistingTemplete += "<td width='150px'>"
        preExistingTemplete += "<div>&lt;contact&gt;&lt;id/&gt;&lt;name&gt;endcustkeyclock163391633916339&lt;/name&gt;&lt;password&gt;Thales@123&lt;/password&gt;&lt;phoneNumber/&gt;&lt;defaultLocale&gt;en&lt;/defaultLocale&gt;&lt;state&gt;ENABLE&lt;/state&gt;&lt;emailId&gt;endcustkeyclock323753237532375@sntinelcloud.com&lt;/emailId&gt;&lt;refId1&gt;ContactrefId1&lt;/refId1&gt;&lt;refId2&gt;ContactrefId2&lt;/refId2&gt;&lt;/contact&gt;<div></div></div>"
        preExistingTemplete += "</td>"
        preExistingTemplete += "<td>242ms</td>"
        preExistingTemplete += "<td>Pass</td>"
        preExistingTemplete += "<td><div><div></div></div></td>"
        preExistingTemplete += "<td><div>[Rint5=16339, Rint5=32375]</div></td>"
        preExistingTemplete += "<td></td>"
        preExistingTemplete += "</tr>"
        preExistingTemplete += "</tbody>"
        preExistingTemplete += "</table>"
        preExistingTemplete += "</div>"
        preExistingTemplete += "</div>"
        preExistingTemplete += "</body>"
        preExistingTemplete += "</html>"
        return preExistingTemplete


    def tableGenerator(self,data):
        preExistingTempleteData = "<tr>"
        preExistingTempleteData += "<td>UpdateXMLData</td>"
        preExistingTempleteData += "<td width='150px'>"
        preExistingTempleteData += "<div>[xml=contact.xml, tags=name;password;emailId, value=endcustkeyclock{{Rint5}}{{Rint5}}{{Rint5}};Thales@123;endcustkeyclock{{Rint5}}{{Rint5}}{{Rint5}}@sntinelcloud.com]</div>"
        preExistingTempleteData += "</td>"
        preExistingTempleteData += "<td>200</td>"
        preExistingTempleteData += "<td>200</td>"
        preExistingTempleteData += "<td width='150px'><div><div></div></div></td>"
        preExistingTempleteData += "<td width='150px'>"
        preExistingTempleteData += "<div>&lt;contact&gt;&lt;id/&gt;&lt;name&gt;endcustkeyclock163391633916339&lt;/name&gt;&lt;password&gt;Thales@123&lt;/password&gt;&lt;phoneNumber/&gt;&lt;defaultLocale&gt;en&lt;/defaultLocale&gt;&lt;state&gt;ENABLE&lt;/state&gt;&lt;emailId&gt;endcustkeyclock323753237532375@sntinelcloud.com&lt;/emailId&gt;&lt;refId1&gt;ContactrefId1&lt;/refId1&gt;&lt;refId2&gt;ContactrefId2&lt;/refId2&gt;&lt;/contact&gt;<div></div></div>"
        preExistingTempleteData += "</td>"
        preExistingTempleteData += "<td>242ms</td>"
        preExistingTempleteData += "<td>Pass</td>"
        preExistingTempleteData += "<td><div><div></div></div></td>"
        preExistingTempleteData += "<td><div>[Rint5=16339, Rint5=32375]</div></td>"
        preExistingTempleteData += "<td></td>"
        preExistingTempleteData += "</tr>"
        return preExistingTempleteData